# Generated by Django 5.0.13 on 2025-03-13 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('pass_word', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.CreateModel(
            name='Check_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
            options={
                'db_table': 'Check_out',
            },
        ),
    ]
